/**
 * rebuild-native.js — Rebuild native modules for Electron
 *
 * Workaround for node-pty's winpty.gyp calling .bat files via cmd /c
 * which fails when the project path contains spaces.
 *
 * Strategy:
 * 1. Patch winpty.gyp to remove cmd /c calls (hardcode commit hash + include dir)
 * 2. Generate GenVersion.h manually
 * 3. Create SUBST drive K: to provide a spaceless path
 * 4. Run node-gyp rebuild for node-pty against Electron ABI
 * 5. Run electron-builder install-app-deps for better-sqlite3
 * 6. Remove SUBST drive
 *
 * Usage: node scripts/rebuild-native.js
 * Requirements: MSVC 2022, Python 3, Electron in devDependencies
 */

const { execSync } = require('child_process')
const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const ELECTRON_VERSION = require(path.join(ROOT, 'node_modules', 'electron', 'package.json')).version

console.log(`[rebuild-native] Electron ${ELECTRON_VERSION}, arch=x64`)
console.log(`[rebuild-native] Project root: ${ROOT}`)

// ── Step 1: Patch winpty.gyp ──────────────────────────────
const gypPath = path.join(ROOT, 'node_modules', 'node-pty', 'deps', 'winpty', 'src', 'winpty.gyp')
let gyp = fs.readFileSync(gypPath, 'utf-8')

const commitHashOrig = `'<!(cmd /c "cd shared && GetCommitHash.bat")'`
const updateGenOrig = `'<!(cmd /c "cd shared && UpdateGenVersion.bat <(WINPTY_COMMIT_HASH)")'`

if (gyp.includes(commitHashOrig)) {
  gyp = gyp.replace(commitHashOrig, `'vendored'`)
  console.log('[rebuild-native] Patched WINPTY_COMMIT_HASH')
}
if (gyp.includes(updateGenOrig)) {
  gyp = gyp.replace(updateGenOrig, `'gen'`)
  console.log('[rebuild-native] Patched UpdateGenVersion include_dirs')
}

fs.writeFileSync(gypPath, gyp)

// ── Step 2: Generate GenVersion.h ─────────────────────────
const versionFile = path.join(ROOT, 'node_modules', 'node-pty', 'deps', 'winpty', 'VERSION.txt')
const version = fs.readFileSync(versionFile, 'utf-8').trim()
const genDir = path.join(ROOT, 'node_modules', 'node-pty', 'deps', 'winpty', 'src', 'gen')
fs.mkdirSync(genDir, { recursive: true })
fs.writeFileSync(path.join(genDir, 'GenVersion.h'),
  `// AUTO-GENERATED by rebuild-native.js\nconst char GenVersion_Version[] = "${version}";\nconst char GenVersion_Commit[] = "vendored";\n`
)
console.log(`[rebuild-native] Generated GenVersion.h (${version})`)

// ── Step 3: SUBST drive for spaceless path ────────────────
const DRIVE = 'K:'
try { execSync(`subst ${DRIVE} /d`, { stdio: 'ignore' }) } catch {}
execSync(`subst ${DRIVE} "${ROOT}"`)
console.log(`[rebuild-native] SUBST ${DRIVE} -> ${ROOT}`)

try {
  // ── Step 4: Rebuild node-pty ──────────────────────────────
  console.log('[rebuild-native] Rebuilding node-pty...')
  execSync(
    `npx node-gyp rebuild --runtime=electron --target=${ELECTRON_VERSION} --arch=x64 --dist-url=https://electronjs.org/headers`,
    { cwd: `${DRIVE}\\node_modules\\node-pty`, stdio: 'inherit' }
  )

  // Verify
  const ptyNode = path.join(ROOT, 'node_modules', 'node-pty', 'build', 'Release', 'pty.node')
  if (!fs.existsSync(ptyNode)) throw new Error('pty.node not found after rebuild')
  console.log('[rebuild-native] node-pty OK: pty.node built')

  // ── Step 5: Rebuild better-sqlite3 ──────────────────────
  console.log('[rebuild-native] Rebuilding better-sqlite3...')
  execSync(
    `npx @electron/rebuild -v ${ELECTRON_VERSION} -m . --only better-sqlite3 --force`,
    { cwd: `${DRIVE}\\`, stdio: 'inherit' }
  )

  const sqliteNode = path.join(ROOT, 'node_modules', 'better-sqlite3', 'build', 'Release', 'better_sqlite3.node')
  if (!fs.existsSync(sqliteNode)) throw new Error('better_sqlite3.node not found after rebuild')
  console.log('[rebuild-native] better-sqlite3 OK: better_sqlite3.node built')

} finally {
  // ── Step 6: Remove SUBST ──────────────────────────────────
  try { execSync(`subst ${DRIVE} /d`, { stdio: 'ignore' }) } catch {}
  console.log(`[rebuild-native] Removed SUBST ${DRIVE}`)
}

console.log('[rebuild-native] All native modules rebuilt successfully for Electron ' + ELECTRON_VERSION)
